### ISSUE TITLE
Add statistics about connections and usage

### ISSUE THREAD

**Issue by fabriziomello** [envoy-postgres/postgresql-proxy#1]
Statistics about connections and usage, in a similar way to what PgBouncer provides with the SHOW STATS command. These will be provided for completeness, and for scenarios where no connection pool is present.

In this first version we'll do not aggregate statistics by database, just by cluster.

Some statistics to add for now:

- **sessions**: total number of connections
- **transactions**: total number of Transactions filtered
- **statements**: total number of Statements filtered
- **statements_insert**: total number of INSERTs filtered
- **statements_delete**: total number of DELETEs filtered 
- **statements_update**: total number of UPDATEs filtered
- **statements_select**: total number of SELECTs filtered
- **statements_other**: total number of other Statements filtered

Reference: https://github.com/envoyproxy/envoy/issues/9107

**Comment by ahachete** [comment]
Absolutely agreed. I believe these statistics will provide already useful information for Postgres Operations. Then we can plan future iterations adding even more information and drilling down some of those concepts, like txs (that may be split into committed/rolled back). This set is very good for now and a first ireration.

Waiting to see the code implementing this ;)

**Comment by 3manuek** [comment]
It would be very useful to have counters for the amount of bytes transmitted by each command type. 

This could help to debug changes in size of the returning response for each command group, abnormal data flow or measuring the overall throughput.

**Comment by fabriziomello** [comment]
@3manuek Cool... what if you create other issue then we can discuss more there...

**Comment by fabriziomello** [comment]
After discussing a bit with other people we decided to also drill down the `transactions` metric to expose committed and rollbacked transactions. So the spec of the first metrics changed a bit:

- **errors**: total number of errors filtered
- **sessions**: total number of connections
- **statements**: total number of Statements filtered
- **statements_insert**: total number of INSERTs filtered
- **statements_delete**: total number of DELETEs filtered 
- **statements_update**: total number of UPDATEs filtered
- **statements_select**: total number of SELECTs filtered
- **statements_other**: total number of other Statements filtered
- **transactions**: total number of Transactions filtered
- **transactions_commit**: total number of Committed Transactions filtered
- **transactions_rollback**: total number of RollbackedTransactions filtered
- **warnings**: total number of Warnings filtered
